---
- name: Playbook
  hosts: all
  user: ec2-user
  become: yes
  connection: ssh
  tasks:
      - name: installing apache on Debian family
        command: apt-get -y install apache2
        when: ansible_os_family == 'Debian'  
      - name: installing apache on RedHat family
        command: yum -y install httpd
        when: ansible_os_family == 'RedHat'
