---
- name: Playbook
  hosts: all
  user: ec2-user
  become: yes
  connection: ssh
  tasks:
      - name: adding list of users
        user:
          name: '{{item}}'
          state: present
        loop:
          - user_one
          - user_two
          - user_three
